language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install -r requirements/develop.txt
    - pip install codecov
    - python setup.py develop
script:
  - pycodestyle --show-source --show-pep8 washer
  - coverage run $(which py.test) -m 'not wip' -v tests/unit
after_success:
  - codecov
